# Generated by Django 4.0.2 on 2023-01-26 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(choices=[(1, 'desayuno'), (2, 'almuerzo'), (3, 'cena'), (4, 'snacks')])),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('carbohidratos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grasas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('proteina', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calorias', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cantidad', models.IntegerField(blank=True, default=1, null=True)),
                ('categoria', models.ManyToManyField(to='Fityfeed.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComidaitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ManyToManyField(blank=True, to='Fityfeed.Cliente')),
                ('comida_item', models.ManyToManyField(to='Fityfeed.ComidaItem')),
            ],
        ),
    ]
